name: "TSLint Action"
description: "Runs TSLint"
inputs:
  tslintConfigFile:
    description: "File path to ts config file (client/tsconfig.json)"
    required: true
  pattern:
    description: "Glob pattern to match files (client/**/*.ts)"
    required: true
  token:
    description: "Github token"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
